create table waste
(
    code_waste         integer,
    name_waste         varchar,
    degree_of_danger   varchar,
    hazard_class       varchar,
    kind_of_activity   varchar,
    education_standard varchar,
    id                 bigserial not null
        constraint waste_pk
            primary key
);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3532603, 'Ртутные лампы отработанные', 'Чрезвычайно опасные', '1', 'Замена по технологическому регламенту', 'Не задано', 1);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3532604, 'Люминесцентные трубки отработанные', 'Чрезвычайно опасные', '1', 'Замена по технологическому регламенту', 'Не задано', 2);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3532607, 'Компактные люминесцентные лампы (энергосберегающие) отработанные', 'Чрезвычайно опасные', '1', 'Замена по технологическому регламенту', 'Не задано', 3);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1711700, 'Отходы (куски, обрезки), фанеры, древесно-стружечных плит, древесно-волокнистых плит, заготовок гнутоклееных и плоскоклееных и др.', 'Умеренно опасные', '3', 'Замена мебели, утратившая свои потребительские свойства', 'Не задано', 4);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1721101, 'Опилки древесные промасленные (содержание масел – менее 15%)', 'Умеренно опасные', '3', 'Эксплуатация и ремонт оборудования и автотранспорта', '1,15т на 1т используемых чистых опилок', 5);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3130601, 'Зола от сжигания быстрорастущей древесины, зола от сжигания дров', 'Умеренно опасные', '3', 'Использование МВТ', 'Зольность топлива Аd = 1,1% на рабочую массу местных видов топлива', 6);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3141204, 'Бой шифера', 'Умеренно опасные', '3', 'Ремонт кровли', '9 кг/м2 изолируемой поверхности', 7);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3142404, 'Песок, загрязненный мазутом (содержание мазута – 15% и более)', 'Умеренно опасные', '3', 'Закачка мазута в резервуары', 'Не задано', 8);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3142406, 'Песок, загрязненный маслами (содержание масел – 15% и более)', 'Умеренно опасные', '3', 'Эксплуатация и ремонт оборудования и автотранспорта', 'Не задано', 9);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3143707, 'Отходы асбокартона', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'до 3 кг/м2 изолируемой поверхности', 10);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3164200, 'Шлам от чистки котлов', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'до 0,4 кг/т топлива', 11);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3531001, 'Проволока медная', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 12);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5410202, 'Масла моторные отработанные', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 13);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5412300, 'Смесь нефтепродуктов отработанных', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 14);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5440100, 'Средства охлаждения и смазки', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 15);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5471500, 'Шлам очистки емкостей', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 16);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5492800, 'Отработанные масляные фильтры', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', '0,137 кг/10 тыс. км пробега', 17);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5492900, 'Использованная тара от нефтепродуктов', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 18);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5551300, 'Старые лаки, краски затвердевшие, а также затвердевшие остатки в бочках (др. емкостях)', 'Умеренно опасные', '3', 'Покрасочные работы', 'Не задано', 19);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5710803, 'Пенопласт полистирола', 'Умеренно опасные', '3', 'Растаривание деталей и механизмов', 'Не задано', 20);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5710812, 'АБС-пластик', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 21);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5710831, 'Вышедшие из употребления изделия и материалы из полистирола и его сополимеры', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 22);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5711011, 'Пенополиуретан', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', '1,8 кг/м погонный заменяемой трубы', 23);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5711101, 'Полиамид (брак, обрезки)', 'Умеренно опасные', '3', 'Слесарные работы', 'Не задано', 24);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5711400, 'ПЭТ-бутылки', 'Умеренно опасные', '3', 'Жизнедеятельность персонала', 'Не задано', 25);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5711601, 'Поливинилхлорид', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 26);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5712105, 'Полиэтилен низкого давления', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 27);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5712109, 'Полиэтилен, вышедшие из употребления изделия промышленно-технического назначения', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 28);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5712600, 'Фторопласт', 'Умеренно опасные', '3', 'Слесарные работы', 'Не задано', 29);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5712700, 'Пластмассовые упаковки и емкости с остатками вредного содержимого', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 30);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5712710, 'Пластмассовые отходы в виде тары из-под моющих, чистящих и других аналогичных средств', 'Умеренно опасные', '3', 'Использование моющих и чистящих средств', 'Не задано', 31);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5712711, 'Пластмассовые отходы в виде тары из-под ЛКМ', 'Умеренно опасные', '3', 'Покрасочные работы', 'Не задано', 32);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5712802, 'Полипропилен, бракованные изделия, обрезки изделий', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 33);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5750119, 'Уплотнительные прокладки, манжеты, втулки и т.п. отработанные', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 34);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5750201, 'Изношенные шины с металлокордом', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 35);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5750202, 'Изношенные шины с текстильным кордом', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'Не задано', 36);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5750301, 'Отходы паронита', 'Умеренно опасные', '3', 'Слесарные работы', 'до 25 кг/1 ремонт; до 8 кг/т продукции', 37);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5750905, 'Тормозные композиционные колодки отработанные', 'Умеренно опасные', '3', 'Замена по технологическому регламенту', 'До индикатора износа тормозной колодки', 38);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5820503, 'Ветошь, загрязненная лакокрасочными материалами', 'Умеренно опасные', '3', 'Покрасочные работы', '0,3 кг/т продукции', 39);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5820601, 'Обтирочный материал, загрязненный маслами ', 'Умеренно опасные', '3', 'Эксплуатация и ремонт оборудования и автотранспорта', '2,18 кг/10  тыс. км пробега', 40);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1471501, 'Обувь кожаная рабочая, потерявшая потребительские свойства', 'Малоопасные', '4', 'Замена по технологическому регламенту', '2кг на сотрудника в год', 41);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1710200, 'Опилки натуральной чистой древесины', 'Малоопасные', '4', 'Деревообработка', 'Не задано', 42);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1710203, 'Опилки и стружка при изготовлении оцилиндрованных, столярных и фрезерованных деталей', 'Малоопасные', '4', 'Деревообработка', 'Не задано', 43);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1710700, 'Кусковые отходы натуральной чистой древесины', 'Малоопасные', '4', 'Деревообработка', 'Не задано', 44);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1710702, 'Кусковые отходы от производства столярных и фрезерованных деталей', 'Малоопасные', '4', 'Деревообработка', 'Не задано', 45);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1720200, 'Древесные отходы строительства', 'Малоопасные', '4', 'Реконструкция, ремонт зданий, сооружений', 'Не задано', 46);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1722901, 'Подметь от уборки цехов и территории предприятий по обработке и переработке древесины', 'Малоопасные', '4', 'Деревообработка', 'Не задано', 47);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1870500, 'Отходы рубероида', 'Малоопасные', '4', 'Замена по технологическому регламенту', 'Не задано', 48);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1870601, 'Отходы бумаги и картона от канцелярской деятельности и делопроизводства', 'Малоопасные', '4', 'Канцелярская деятельность и делопроизводство', 'Не задано', 49);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1870605, 'Отходы упаковочного картона незагрязненные', 'Малоопасные', '4', 'Растаривание деталей и механизмов', 'Не задано', 50);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3140812, 'Стеклобой неармированного бесцветного стекла', 'Малоопасные', '4', 'Реконструкция, ремонт зданий, сооружений', 'Не задано', 51);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3140825, 'Отходы стекла «Триплекс»', 'Малоопасные', '4', 'Замена по технологическому регламенту', 'Не задано', 52);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3141401, 'Лом кирпича шамотного', 'Малоопасные', '4', 'Замена по технологическому регламенту', 'Не задано', 53);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3142405, 'Песок, загрязненный маслами (содержание масел – менее 15%)', 'Малоопасные', '4', 'Эксплуатация и ремонт оборудования и автотранспорта', 'Не задано', 54);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3143100, 'Отходы плит минераловатных', 'Малоопасные', '4', 'Замена по технологическому регламенту', 'Не задано', 55);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3143701, 'Отходы асбеста в кусковой форме', 'Малоопасные', '4', 'Замена по технологическому регламенту', 'Не задано', 56);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3144407, 'Абразивная пыль и порошок от шлифования черных металлов (с содер. металлов 50%)', 'Малоопасные', '4', 'Металлообработка', '2,9 кг/1000 обработанных деталей', 57);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3145300, 'Сульфоуголь отработанный', 'Малоопасные', '4', 'Замена по технологическому регламенту', '1т на 1 замену фильтрующего материала', 58);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3510602, 'Металлическая тара, загрязненная ЛКМ', 'Малоопасные', '4', 'Покрасочные работы', 'Не задано', 59);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3534500, 'Батареи (элементы питания) различных моделей отработанные', 'Малоопасные', '4', 'Замена по технологическому регламенту', 'Не задано', 60);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3991300, 'Смешанные отходы строительства', 'Малоопасные', '4', 'Замена по технологическому регламенту', 'Не задано', 61);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5471700, 'Донные отложения мазутных резервуаров', 'Малоопасные', '4', 'Замена по технологическому регламенту', 'Не задано', 62);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5740400, 'Отходы стекловаты', 'Малоопасные', '4', 'Замена по технологическому регламенту', 'Не задано', 63);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5820903, 'Изношенная спецодежда хлопчатобумажная и другая', 'Малоопасные', '4', 'Замена по технологическому регламенту', '12 кг на одного работника', 64);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (8440100, 'Осадки взвешенных веществ от очистки дождевых стоков', 'Малоопасные', '4', 'Замена по технологическому регламенту', 'Не задано', 65);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (9120800, 'Отходы (смет) от уборки территорий промышленных предприятий и организаций', 'Малоопасные', '4', 'Уборка территории и помещений', 'Не задано', 66);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1730200, 'Сучья, ветки, вершины', 'н/о', 'н/о', 'Обрезка объектов растительного мира', 'Не задано', 67);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (1730300, 'Отходы корчевания пней', 'н/о', 'н/о', 'Корчевание ОРМ', 'Не задано', 68);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3140801, 'Стеклобой бесцветный тарный', 'н/о', 'н/о', 'Жизнедеятельность персонала', 'Не задано', 69);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3140804, 'Стеклобой полубелый листовой', 'н/о', 'н/о', 'Жизнедеятельность персонала', 'Не задано', 70);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3141004, 'Асфальтобетон от разборки асфальтовых покрытий', 'н/о', 'н/о', 'Замена по технологическому регламенту', 'Не задано', 71);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3141101, 'Земляные выемки, грунт, образовавшиеся при проведении землеройных работ, не загрязненные опасными веществами', 'н/о', 'н/о', 'Замена по технологическому регламенту', 'Не задано', 72);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3142708, 'Бой железобетонных изделий', 'н/о', 'н/о', 'Замена по технологическому регламенту', 'Не задано', 73);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3142707, 'Бой бетонных изделий', 'н/о', 'н/о', 'Замена по технологическому регламенту', 'Не задано', 74);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3144406, 'Абразивные круги отработанные, лом отработанных абразивных кругов', 'н/о', 'н/о', 'Металлообработка', 'Не задано', 75);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3144411, 'Отработанная шлифовальная шкурка', 'н/о', 'н/о', 'Деревообработка и металлообработка', '0,1 кг/м2 обрабатываемой поверхности', 76);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3511002, 'Стружка стальная незагрязненная', 'н/о', 'н/о', 'Металлообработка', 'Не задано', 77);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3511008, 'Лом стальной несортированный', 'н/о', 'н/о', 'Металлообработка и замена по технологическому регламенту', 'Не задано', 78);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3511102, 'Лом чугунный несортированный', 'н/о', 'н/о', 'Металлообработка и замена по технологическому регламенту', 'Не задано', 79);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3511500, 'Металлические конструкции и детали из железа и стали поврежденные', 'н/о', 'н/о', 'Металлообработка и замена по технологическому регламенту', 'Не задано', 80);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3530405, 'Лом алюминия несортированный', 'н/о', 'н/о', 'Металлообработка и замена по технологическому регламенту', 'Не задано', 81);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3531102, 'Стружка бронзы незагрязненная', 'н/о', 'н/о', 'Металлообработка', 'Не задано', 82);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3531103, 'Лом бронзы несортированный', 'н/о', 'н/о', 'Металлообработка и замена по технологическому регламенту', 'Не задано', 83);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3531202, 'Стружка латуни незагрязненная', 'н/о', 'н/о', 'Металлообработка', 'Не задано', 84);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3531203, 'Лом латуни несортированный', 'н/о', 'н/о', 'Металлообработка и замена по технологическому регламенту', 'Не задано', 85);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (5740100, 'Отходы стеклотканей', 'н/о', 'н/о', 'Замена по технологическому регламенту', 'Не задано', 86);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (9120400, 'Отходы производства, подобные отходам жизнедеятельности населения', 'н/о', 'н/о', 'Жизнедеятельность персонала', '54 кг на 1 сотрудника', 87);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (9120500, 'Уличный и дворовой смет', 'н/о', 'н/о', 'Уборка территорий', 'Не задано', 88);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (9121100, 'Растительные отходы от уборки территорий садов, парков, скверов, кладбищ и иных озелененных территорий', 'н/о', 'н/о', 'Уборка территорий', 'Не задано', 89);
INSERT INTO public.waste (code_waste, name_waste, degree_of_danger, hazard_class, kind_of_activity, education_standard, id) VALUES (3532201, 'Свинцовые аккумуляторы отработанные неповрежденные с неслитым электролитом', 'Чрезвычайно опасные', '1', 'Замена по технологическому регламенту', 'Не задано', 90);